name: Rijksmuseum API Tests CI

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Step 3: Cache Maven dependencies for faster builds
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Install dependencies and run tests
    - name: Build with Maven and Run Tests
      run: mvn clean test

    # Step 5: Generate Allure Results
    - name: Generate Allure Report
      run: |
        mvn allure:report
        allure generate target/allure-results -o target/allure-report --clean

    # Step 6: Upload Allure Report as an Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/allure-report

# Merge rules after passing all tests**
jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Ensure all checks have passed before merge
      run: echo "All tests have passed. Proceed to merge if needed."
